server: 
  port: 8765
spring: 
  application: 
    name: eurekarabbit
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
